// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4YD0YTWSJ9AVGAYuiIk3q-WB9n55I1zE',
    appId: '1:262215574433:web:0e7a6bb0689d32e3ed21e0',
    messagingSenderId: '262215574433',
    projectId: 'flash-chat-1eece',
    authDomain: 'flash-chat-1eece.firebaseapp.com',
    storageBucket: 'flash-chat-1eece.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDPu8-X7BsIdUmnHe-ZdgR9BGdg4HbaG4',
    appId: '1:262215574433:android:96526dbd08de0db6ed21e0',
    messagingSenderId: '262215574433',
    projectId: 'flash-chat-1eece',
    storageBucket: 'flash-chat-1eece.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABBwr4pdwKcjyu-lJD1x5pcsCNYUOXUN8',
    appId: '1:262215574433:ios:392b1381fb09bcf6ed21e0',
    messagingSenderId: '262215574433',
    projectId: 'flash-chat-1eece',
    storageBucket: 'flash-chat-1eece.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABBwr4pdwKcjyu-lJD1x5pcsCNYUOXUN8',
    appId: '1:262215574433:ios:1ae670d8dd0c073fed21e0',
    messagingSenderId: '262215574433',
    projectId: 'flash-chat-1eece',
    storageBucket: 'flash-chat-1eece.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
